steps:
  - label: "language check"
    command: echo "Watch your damn launguage!" | buildkite-agent annotate --style "warning"
    if: build.message =~ /.*fuck.*/

  - label: ":construction_worker: Build"
    command: echo "Build the rocket" > somefile.txt
    key: build

  - label: ":white_check_mark: Test"
    command: cat somefile.txt
    key: test
    depends_on: build

  - label: "Dynamic Last Step"
    command: .buildkite/generate-moar-steps.sh | buildkite-agent pipeline upload
    key: deploy
